package com.continuum.nova.utils;

import net.minecraft.util.ResourceLocation;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.List;

public class Utils {
    private Utils() {}

    static boolean exists(Object objectToCheck)
    {
        return objectToCheck != null;
    }

    public static void initGuiTextureLocations(List<ResourceLocation> locations) {
        locations.add(new ResourceLocation("gui/bars"));
        locations.add(new ResourceLocation("gui/book"));
        locations.add(new ResourceLocation("gui/demo_background"));
        locations.add(new ResourceLocation("gui/icons"));
        locations.add(new ResourceLocation("gui/resource_packs"));
        locations.add(new ResourceLocation("gui/server_selection"));
        locations.add(new ResourceLocation("gui/spectator_widgets"));
        // locations.add(new ResourceLocation("gui/stream_indicator")); // non-square texture, breaks
        locations.add(new ResourceLocation("gui/widgets"));
        locations.add(new ResourceLocation("gui/world_selection"));
        locations.add(new ResourceLocation("gui/achievement/achievement_background"));
        locations.add(new ResourceLocation("gui/achievement/achievement_icons"));
        locations.add(new ResourceLocation("gui/container/anvil"));
        locations.add(new ResourceLocation("gui/container/beacon"));
        locations.add(new ResourceLocation("gui/container/brewing_stand"));
        locations.add(new ResourceLocation("gui/container/crafting_table"));
        locations.add(new ResourceLocation("gui/container/dispenser"));
        locations.add(new ResourceLocation("gui/container/enchanting_table"));
        locations.add(new ResourceLocation("gui/container/furnace"));
        locations.add(new ResourceLocation("gui/container/generic_54"));
        locations.add(new ResourceLocation("gui/container/hopper"));
        locations.add(new ResourceLocation("gui/container/horse"));
        locations.add(new ResourceLocation("gui/container/inventory"));
        locations.add(new ResourceLocation("gui/container/stats_icons"));
        locations.add(new ResourceLocation("gui/container/villager"));
        locations.add(new ResourceLocation("gui/container/creative_inventory/tabs"));
        locations.add(new ResourceLocation("gui/container/creative_inventory/tab_inventory"));
        locations.add(new ResourceLocation("gui/container/creative_inventory/tab_items"));
        locations.add(new ResourceLocation("gui/container/creative_inventory/tab_item_search"));
        locations.add(new ResourceLocation("gui/presets/chaos"));
        locations.add(new ResourceLocation("gui/presets/delight"));
        locations.add(new ResourceLocation("gui/presets/drought"));
        locations.add(new ResourceLocation("gui/presets/isles"));
        locations.add(new ResourceLocation("gui/presets/luck"));
        locations.add(new ResourceLocation("gui/presets/madness"));
        locations.add(new ResourceLocation("gui/presets/water"));
        locations.add(new ResourceLocation("gui/title/minecraft"));
        locations.add(new ResourceLocation("gui/title/mojang"));
        locations.add(new ResourceLocation("gui/title/background/panorama_0"));
        locations.add(new ResourceLocation("gui/title/background/panorama_1"));
        locations.add(new ResourceLocation("gui/title/background/panorama_2"));
        locations.add(new ResourceLocation("gui/title/background/panorama_3"));
        locations.add(new ResourceLocation("gui/title/background/panorama_4"));
        locations.add(new ResourceLocation("gui/title/background/panorama_5"));
    }

    public static void initFontTextureLocations(List<ResourceLocation> locations) {
        locations.add(new ResourceLocation("font/ascii"));
        locations.add(new ResourceLocation("font/ascii_sga"));
        locations.add(new ResourceLocation("font/unicode_page_00"));
        locations.add(new ResourceLocation("font/unicode_page_01"));
        locations.add(new ResourceLocation("font/unicode_page_02"));
        locations.add(new ResourceLocation("font/unicode_page_03"));
        locations.add(new ResourceLocation("font/unicode_page_04"));
        locations.add(new ResourceLocation("font/unicode_page_05"));
        locations.add(new ResourceLocation("font/unicode_page_06"));
        locations.add(new ResourceLocation("font/unicode_page_07"));
        locations.add(new ResourceLocation("font/unicode_page_09"));
        locations.add(new ResourceLocation("font/unicode_page_0a"));
        locations.add(new ResourceLocation("font/unicode_page_0b"));
        locations.add(new ResourceLocation("font/unicode_page_0c"));
        locations.add(new ResourceLocation("font/unicode_page_0d"));
        locations.add(new ResourceLocation("font/unicode_page_0e"));
        locations.add(new ResourceLocation("font/unicode_page_0f"));
        locations.add(new ResourceLocation("font/unicode_page_10"));
        locations.add(new ResourceLocation("font/unicode_page_11"));
        locations.add(new ResourceLocation("font/unicode_page_12"));
        locations.add(new ResourceLocation("font/unicode_page_13"));
        locations.add(new ResourceLocation("font/unicode_page_14"));
        locations.add(new ResourceLocation("font/unicode_page_15"));
        locations.add(new ResourceLocation("font/unicode_page_16"));
        locations.add(new ResourceLocation("font/unicode_page_17"));
        locations.add(new ResourceLocation("font/unicode_page_18"));
        locations.add(new ResourceLocation("font/unicode_page_19"));
        locations.add(new ResourceLocation("font/unicode_page_1a"));
        locations.add(new ResourceLocation("font/unicode_page_1b"));
        locations.add(new ResourceLocation("font/unicode_page_1c"));
        locations.add(new ResourceLocation("font/unicode_page_1d"));
        locations.add(new ResourceLocation("font/unicode_page_1e"));
        locations.add(new ResourceLocation("font/unicode_page_1f"));
        locations.add(new ResourceLocation("font/unicode_page_20"));
        locations.add(new ResourceLocation("font/unicode_page_21"));
        locations.add(new ResourceLocation("font/unicode_page_22"));
        locations.add(new ResourceLocation("font/unicode_page_23"));
        locations.add(new ResourceLocation("font/unicode_page_24"));
        locations.add(new ResourceLocation("font/unicode_page_25"));
        locations.add(new ResourceLocation("font/unicode_page_26"));
        locations.add(new ResourceLocation("font/unicode_page_27"));
        locations.add(new ResourceLocation("font/unicode_page_28"));
        locations.add(new ResourceLocation("font/unicode_page_29"));
        locations.add(new ResourceLocation("font/unicode_page_2a"));
        locations.add(new ResourceLocation("font/unicode_page_2b"));
        locations.add(new ResourceLocation("font/unicode_page_2c"));
        locations.add(new ResourceLocation("font/unicode_page_2d"));
        locations.add(new ResourceLocation("font/unicode_page_2e"));
        locations.add(new ResourceLocation("font/unicode_page_2f"));
        locations.add(new ResourceLocation("font/unicode_page_30"));
        locations.add(new ResourceLocation("font/unicode_page_31"));
        locations.add(new ResourceLocation("font/unicode_page_32"));
        locations.add(new ResourceLocation("font/unicode_page_33"));
        locations.add(new ResourceLocation("font/unicode_page_34"));
        locations.add(new ResourceLocation("font/unicode_page_35"));
        locations.add(new ResourceLocation("font/unicode_page_36"));
        locations.add(new ResourceLocation("font/unicode_page_37"));
        locations.add(new ResourceLocation("font/unicode_page_38"));
        locations.add(new ResourceLocation("font/unicode_page_39"));
        locations.add(new ResourceLocation("font/unicode_page_3a"));
        locations.add(new ResourceLocation("font/unicode_page_3b"));
        locations.add(new ResourceLocation("font/unicode_page_3c"));
        locations.add(new ResourceLocation("font/unicode_page_3d"));
        locations.add(new ResourceLocation("font/unicode_page_3e"));
        locations.add(new ResourceLocation("font/unicode_page_3f"));
        locations.add(new ResourceLocation("font/unicode_page_40"));
        locations.add(new ResourceLocation("font/unicode_page_41"));
        locations.add(new ResourceLocation("font/unicode_page_42"));
        locations.add(new ResourceLocation("font/unicode_page_43"));
        locations.add(new ResourceLocation("font/unicode_page_44"));
        locations.add(new ResourceLocation("font/unicode_page_45"));
        locations.add(new ResourceLocation("font/unicode_page_46"));
        locations.add(new ResourceLocation("font/unicode_page_47"));
        locations.add(new ResourceLocation("font/unicode_page_48"));
        locations.add(new ResourceLocation("font/unicode_page_49"));
        locations.add(new ResourceLocation("font/unicode_page_4a"));
        locations.add(new ResourceLocation("font/unicode_page_4b"));
        locations.add(new ResourceLocation("font/unicode_page_4c"));
        locations.add(new ResourceLocation("font/unicode_page_4d"));
        locations.add(new ResourceLocation("font/unicode_page_4e"));
        locations.add(new ResourceLocation("font/unicode_page_4f"));
        locations.add(new ResourceLocation("font/unicode_page_50"));
        locations.add(new ResourceLocation("font/unicode_page_51"));
        locations.add(new ResourceLocation("font/unicode_page_52"));
        locations.add(new ResourceLocation("font/unicode_page_53"));
        locations.add(new ResourceLocation("font/unicode_page_54"));
        locations.add(new ResourceLocation("font/unicode_page_55"));
        locations.add(new ResourceLocation("font/unicode_page_56"));
        locations.add(new ResourceLocation("font/unicode_page_57"));
        locations.add(new ResourceLocation("font/unicode_page_58"));
        locations.add(new ResourceLocation("font/unicode_page_59"));
        locations.add(new ResourceLocation("font/unicode_page_5a"));
        locations.add(new ResourceLocation("font/unicode_page_5b"));
        locations.add(new ResourceLocation("font/unicode_page_5c"));
        locations.add(new ResourceLocation("font/unicode_page_5d"));
        locations.add(new ResourceLocation("font/unicode_page_5e"));
        locations.add(new ResourceLocation("font/unicode_page_5f"));
        locations.add(new ResourceLocation("font/unicode_page_60"));
        locations.add(new ResourceLocation("font/unicode_page_61"));
        locations.add(new ResourceLocation("font/unicode_page_62"));
        locations.add(new ResourceLocation("font/unicode_page_63"));
        locations.add(new ResourceLocation("font/unicode_page_64"));
        locations.add(new ResourceLocation("font/unicode_page_65"));
        locations.add(new ResourceLocation("font/unicode_page_66"));
        locations.add(new ResourceLocation("font/unicode_page_67"));
        locations.add(new ResourceLocation("font/unicode_page_68"));
        locations.add(new ResourceLocation("font/unicode_page_69"));
        locations.add(new ResourceLocation("font/unicode_page_6a"));
        locations.add(new ResourceLocation("font/unicode_page_6b"));
        locations.add(new ResourceLocation("font/unicode_page_6c"));
        locations.add(new ResourceLocation("font/unicode_page_6d"));
        locations.add(new ResourceLocation("font/unicode_page_6e"));
        locations.add(new ResourceLocation("font/unicode_page_6f"));
        locations.add(new ResourceLocation("font/unicode_page_70"));
        locations.add(new ResourceLocation("font/unicode_page_71"));
        locations.add(new ResourceLocation("font/unicode_page_72"));
        locations.add(new ResourceLocation("font/unicode_page_73"));
        locations.add(new ResourceLocation("font/unicode_page_74"));
        locations.add(new ResourceLocation("font/unicode_page_75"));
        locations.add(new ResourceLocation("font/unicode_page_76"));
        locations.add(new ResourceLocation("font/unicode_page_77"));
        locations.add(new ResourceLocation("font/unicode_page_78"));
        locations.add(new ResourceLocation("font/unicode_page_79"));
        locations.add(new ResourceLocation("font/unicode_page_7a"));
        locations.add(new ResourceLocation("font/unicode_page_7b"));
        locations.add(new ResourceLocation("font/unicode_page_7c"));
        locations.add(new ResourceLocation("font/unicode_page_7d"));
        locations.add(new ResourceLocation("font/unicode_page_7e"));
        locations.add(new ResourceLocation("font/unicode_page_7f"));
        locations.add(new ResourceLocation("font/unicode_page_80"));
        locations.add(new ResourceLocation("font/unicode_page_81"));
        locations.add(new ResourceLocation("font/unicode_page_82"));
        locations.add(new ResourceLocation("font/unicode_page_83"));
        locations.add(new ResourceLocation("font/unicode_page_84"));
        locations.add(new ResourceLocation("font/unicode_page_85"));
        locations.add(new ResourceLocation("font/unicode_page_86"));
        locations.add(new ResourceLocation("font/unicode_page_87"));
        locations.add(new ResourceLocation("font/unicode_page_88"));
        locations.add(new ResourceLocation("font/unicode_page_89"));
        locations.add(new ResourceLocation("font/unicode_page_8a"));
        locations.add(new ResourceLocation("font/unicode_page_8b"));
        locations.add(new ResourceLocation("font/unicode_page_8c"));
        locations.add(new ResourceLocation("font/unicode_page_8d"));
        locations.add(new ResourceLocation("font/unicode_page_8e"));
        locations.add(new ResourceLocation("font/unicode_page_8f"));
        locations.add(new ResourceLocation("font/unicode_page_90"));
        locations.add(new ResourceLocation("font/unicode_page_91"));
        locations.add(new ResourceLocation("font/unicode_page_92"));
        locations.add(new ResourceLocation("font/unicode_page_93"));
        locations.add(new ResourceLocation("font/unicode_page_94"));
        locations.add(new ResourceLocation("font/unicode_page_95"));
        locations.add(new ResourceLocation("font/unicode_page_96"));
        locations.add(new ResourceLocation("font/unicode_page_97"));
        locations.add(new ResourceLocation("font/unicode_page_98"));
        locations.add(new ResourceLocation("font/unicode_page_99"));
        locations.add(new ResourceLocation("font/unicode_page_9a"));
        locations.add(new ResourceLocation("font/unicode_page_9b"));
        locations.add(new ResourceLocation("font/unicode_page_9c"));
        locations.add(new ResourceLocation("font/unicode_page_9d"));
        locations.add(new ResourceLocation("font/unicode_page_9e"));
        locations.add(new ResourceLocation("font/unicode_page_9f"));
        locations.add(new ResourceLocation("font/unicode_page_a0"));
        locations.add(new ResourceLocation("font/unicode_page_a1"));
        locations.add(new ResourceLocation("font/unicode_page_a2"));
        locations.add(new ResourceLocation("font/unicode_page_a3"));
        locations.add(new ResourceLocation("font/unicode_page_a4"));
        locations.add(new ResourceLocation("font/unicode_page_a5"));
        locations.add(new ResourceLocation("font/unicode_page_a6"));
        locations.add(new ResourceLocation("font/unicode_page_a7"));
        locations.add(new ResourceLocation("font/unicode_page_a8"));
        locations.add(new ResourceLocation("font/unicode_page_a9"));
        locations.add(new ResourceLocation("font/unicode_page_aa"));
        locations.add(new ResourceLocation("font/unicode_page_ab"));
        locations.add(new ResourceLocation("font/unicode_page_ac"));
        locations.add(new ResourceLocation("font/unicode_page_ad"));
        locations.add(new ResourceLocation("font/unicode_page_ae"));
        locations.add(new ResourceLocation("font/unicode_page_af"));
        locations.add(new ResourceLocation("font/unicode_page_b0"));
        locations.add(new ResourceLocation("font/unicode_page_b1"));
        locations.add(new ResourceLocation("font/unicode_page_b2"));
        locations.add(new ResourceLocation("font/unicode_page_b3"));
        locations.add(new ResourceLocation("font/unicode_page_b4"));
        locations.add(new ResourceLocation("font/unicode_page_b5"));
        locations.add(new ResourceLocation("font/unicode_page_b6"));
        locations.add(new ResourceLocation("font/unicode_page_b7"));
        locations.add(new ResourceLocation("font/unicode_page_b8"));
        locations.add(new ResourceLocation("font/unicode_page_b9"));
        locations.add(new ResourceLocation("font/unicode_page_ba"));
        locations.add(new ResourceLocation("font/unicode_page_bb"));
        locations.add(new ResourceLocation("font/unicode_page_bc"));
        locations.add(new ResourceLocation("font/unicode_page_bd"));
        locations.add(new ResourceLocation("font/unicode_page_be"));
        locations.add(new ResourceLocation("font/unicode_page_bf"));
        locations.add(new ResourceLocation("font/unicode_page_c0"));
        locations.add(new ResourceLocation("font/unicode_page_c1"));
        locations.add(new ResourceLocation("font/unicode_page_c2"));
        locations.add(new ResourceLocation("font/unicode_page_c3"));
        locations.add(new ResourceLocation("font/unicode_page_c4"));
        locations.add(new ResourceLocation("font/unicode_page_c5"));
        locations.add(new ResourceLocation("font/unicode_page_c6"));
        locations.add(new ResourceLocation("font/unicode_page_c7"));
        locations.add(new ResourceLocation("font/unicode_page_c8"));
        locations.add(new ResourceLocation("font/unicode_page_c9"));
        locations.add(new ResourceLocation("font/unicode_page_ca"));
        locations.add(new ResourceLocation("font/unicode_page_cb"));
        locations.add(new ResourceLocation("font/unicode_page_cc"));
        locations.add(new ResourceLocation("font/unicode_page_cd"));
        locations.add(new ResourceLocation("font/unicode_page_ce"));
        locations.add(new ResourceLocation("font/unicode_page_cf"));
        locations.add(new ResourceLocation("font/unicode_page_d0"));
        locations.add(new ResourceLocation("font/unicode_page_d1"));
        locations.add(new ResourceLocation("font/unicode_page_d2"));
        locations.add(new ResourceLocation("font/unicode_page_d3"));
        locations.add(new ResourceLocation("font/unicode_page_d4"));
        locations.add(new ResourceLocation("font/unicode_page_d5"));
        locations.add(new ResourceLocation("font/unicode_page_d6"));
        locations.add(new ResourceLocation("font/unicode_page_d7"));
        locations.add(new ResourceLocation("font/unicode_page_f9"));
        locations.add(new ResourceLocation("font/unicode_page_fa"));
        locations.add(new ResourceLocation("font/unicode_page_fb"));
        locations.add(new ResourceLocation("font/unicode_page_fc"));
        locations.add(new ResourceLocation("font/unicode_page_fd"));
        locations.add(new ResourceLocation("font/unicode_page_fe"));
        locations.add(new ResourceLocation("font/unicode_page_ff"));
    }

    public static void initFreeTextures(List<ResourceLocation> locations) {
        locations.add(new ResourceLocation("textures/misc/unknown_server.png"));
        locations.add(new ResourceLocation("textures/gui/options_background.png"));
    }

    public static byte[] getImageData(BufferedImage image) {
        byte[] convertedImageData = new byte[image.getWidth()*image.getHeight()*4];
        int counter = 0;
        for (int y = 0; y < image.getHeight(); y ++) {
            for (int x = 0;x<image.getWidth();x++) {

                Color c = new Color(image.getRGB(x,y),image.getColorModel().hasAlpha());

                convertedImageData[counter] =(byte) (c.getRed());
                convertedImageData[counter + 1] = (byte)(c.getGreen());
                convertedImageData[counter + 2] = (byte)(c.getBlue());
                convertedImageData[counter + 3] = (byte) (image.getColorModel().getNumComponents() == 3 ? 255 : c.getAlpha());
                counter+=4;
            }
        }
        return convertedImageData;
    }
}
